export const Strings = {
    'please_select_app': 'Please Select an App',
    'dynamic_forms': 'Dynamic Forms',
    'dyanamic_polls': 'Dynamic Polls',
    'new_form': 'New Form',
    'form_list': 'Form List',
    'form_details': 'Form Details',
    'new_poll': 'New Poll',
    'poll_list': 'Poll List',
    'poll_details': 'Poll Details',
    'poll_summary': 'Poll Summary',
    'form_builder': 'Form Builder',
    'submit': 'Submit',
    'cancel': 'Cancel',
    'home': 'Home',
    'success': 'Success',
    'error': 'Error',
    'form_submitted': 'Form submitted successfully!',
    'form_already_submitted': 'This form has already been submitted.',
    'poll_submitted': 'Poll submitted successfully!',
    'poll_already_submitted': 'This poll has already been submitted.',
    'reset_poll_data': 'Reset Poll Data',
    'poll_reset_success': 'Poll data reset successfully!',
    'date_and_time': 'Date and Time',
    'select_poll_type': 'Select Poll Type',
}